# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

target 'TTDownloader' do
pod 'AFNetworking', '1.3.4'
end

target 'TTDownloaderTests' do
pod 'AFNetworking', '1.3.4'
end

